name: deploy

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKEHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKEHUB_USERNAME }}/threader

      - name: SSH into Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd api-threder-intern && docker compose pull && docker compose up -d

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Required mail subject:
          subject: Github Actions job result
          # Recipient :
          to: luonglkvn100@gmail.com | vanduccntt036@gmail.com | tamnguyen231173@gmail.com | vicn1708@gmail.com
          # Required sender full name (address can be skipped):
          from: Deploying state
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
